### ISSUE TITLE
能支持TChart控件吗？

### ISSUE THREAD

**Issue by tina2elva** [ying32/liblcl#16]
能支持TChart控件吗？

**Comment by ying32** [comment]
TChart控件太大了，而且有版权啥的，不适合打包到标准库里，如果需要的话可以参考源码做个简易的。
另外go的例子里面其实有两个简易的chart样例。

**Comment by tina2elva** [comment]
谢谢 因为要做动态的。哪几个例子看着不合适，已经用简单用canvas自己画图解决了
