### ISSUE TITLE
能不能用个什么参数或者设置个变量之类的不输出 Library Version

### ISSUE THREAD

**Issue by hick** [ying32/liblcl#6]
能不能用个什么参数或者 Go 的 init() 函数设置个变量之类的不输出 Library Version ? 

调试的时候输出还好, 就是我同时作为 GUI 和命令行工具的整合以后(双击才打开 GUI), 命令行总是会输出  Library Version: 2.0.9 这样的如下

![image](https://user-images.githubusercontent.com/38886/187951919-ef868e78-fe04-4cee-928d-6e7710cd2d02.png)

谢谢

**Comment by ying32** [comment]
目前没有办法，只能你自己修改代码去掉。。。

**Comment by hick** [comment]
> 目前没有办法，只能你自己修改代码去掉。。。

哈哈哈, thx 我也是用的不多,  原来以为是 liblcl.dll 里输出的.  经提醒才搜索发现,  好像应该算  govcl 这个仓库的, 搜到 在[ init.go 的 init() 函数](https://github.com/ying32/govcl/blob/b505edd35ca390dd3721330a99031385429fe48c/vcl/init.go) 里输出的了.  难怪昨天提单的时候没搜到,

**Comment by hick** [comment]
搞定了  thx
