### ISSUE TITLE
Mac编译时出现内存不足的问题

### ISSUE THREAD

**Issue by lstarboy** [ying32/liblcl#8]
Lazarus IDE2.2.0和IDE2.2.4 Mac版本编译liblcl时，会发生如下错误：

LazarusDef.inc (1040,1) Error: Compilation raised exception internally
Fatal: No memory left.

事实上内存还有40G+可以使用，上面是一些资源定义，怀疑与此有关：

如 (Name: 'rsSelectionFontTitle';  ValuePtr: @rsSelectionFontTitle)

大神们赶紧解决一下！谢谢！

**Comment by ying32** [comment]
Lazarus2.2.4我还没用上，但2.2.2我用了没这问题。你这40G不会是ROM吧？他这报错要求的事RAM哦

**Comment by lstarboy** [comment]
64G内存的Mac Mini机器只用掉16G左右，肯定不是ROM；FPC官网也查到一些类似的no memory left错误，好像跟编译器有关；我编译liblcl的目的是为了使用最新的几个控件，如果能帮助编一个最新版的各个平台的二进制也行，不知liblcl官网啥时能发布个二进制版本啊？

**Comment by ying32** [comment]
你可以用2.2.2版本试试。暂时没有计划发布

**Comment by lstarboy** [comment]
@ying32 我用2.2.2版本依然出一样的问题，感觉跟我的Mac环境（MacOS Ventura 13.0）或FPC版本（3.2.2 intelarm64）相关，请问你的环境是咋样的？能否单独给我发一个您编好的Mac liblcl.dylib（email: lstarboy@163.com）?

**Comment by lstarboy** [comment]
@ying32 搞定了，应该使用dev分支的代码才行，谢谢！！！

**Comment by ying32** [comment]
这就怪事了，master分支的也没事啊，我的是10.13.6版本的。。。 arm的。。汗，我还没有这个可用。。没法编译出来arm的。

**Comment by lstarboy** [comment]
我Mac机器是Intel的
