### ISSUE TITLE
TStrings 相关的函数，通过FFI调用会出现abstract method called错误

### ISSUE THREAD

**Issue by dongnanyanhai** [ying32/liblcl#9]
我通过PHP FFI来调用liblcl，使用Strings_Create创建对象后，对改对象进行Strings_Add、Strings_SetText等函数时，都会弹出abstract method called。

我使用的是dev版本。

**Comment by dongnanyanhai** [comment]
目前通过Memo_GetLines得到的TStrings对象去进行Add、SetText等操作，是正常的。

暂时可以确定FFI调用liblcl的方式是没问题，可能是TStrings相关函数的实现问题。

**Comment by ying32** [comment]
这个是你对pascal不熟，TStrings是不能直接create的，应该用TStringList，

**Comment by dongnanyanhai** [comment]
> 这个是你对pascal不熟，TStrings是不能直接create的，应该用TStringList，

好的我用TStringList来操作，谢谢！

**Comment by dongnanyanhai** [comment]
问题解决了，谢谢！
